import { MigrationInterface, QueryRunner } from "typeorm";

export class UpdateProjectsTable1764764646470 implements MigrationInterface {
    name = 'UpdateProjectsTable1764764646470'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "voucher_types" DROP CONSTRAINT "FK_189fe983f7ad425d7b9399deb11"`);
        await queryRunner.query(`ALTER TABLE "fiscal_years" DROP CONSTRAINT "FK_12c06a42d8814383cfeca9abc83"`);
        await queryRunner.query(`ALTER TABLE "tax_categories" DROP CONSTRAINT "FK_3dc030fc235c86c139927bbfa55"`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP CONSTRAINT "FK_b22c8136b3e83352b0013224801"`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP CONSTRAINT "FK_f7ea327e4100ce4d6002ecdd12b"`);
        await queryRunner.query(`ALTER TABLE "cost_centers" DROP CONSTRAINT "FK_966404fc47b7566686a92802ef9"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP CONSTRAINT "FK_f0e29920aaf871f3eddbea69f0d"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP CONSTRAINT "FK_ebcc29963874e55053e8ee80be5"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_c8708288b8e6a060ed7b9e1a226"`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP CONSTRAINT "FK_6a9681499416e80c1ffac4fe86c"`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP CONSTRAINT "FK_62193e7cad0c29598758ad187d0"`);
        await queryRunner.query(`ALTER TABLE "reconciliations" DROP CONSTRAINT "FK_a895f63f3a83d3c7bbaf2f3d6e0"`);
        await queryRunner.query(`ALTER TABLE "journal_entry_lines" DROP CONSTRAINT "FK_4a4fcd732e7b109880444ebc9c1"`);
        await queryRunner.query(`ALTER TABLE "journal_entry_lines" DROP CONSTRAINT "FK_b40d116356fb32866615bfa10d6"`);
        await queryRunner.query(`ALTER TABLE "journal_entries" DROP CONSTRAINT "FK_435ac51210483ad504efff69a40"`);
        await queryRunner.query(`ALTER TABLE "journal_entries" DROP CONSTRAINT "FK_e077d1bd97565c550c745399139"`);
        await queryRunner.query(`ALTER TABLE "journal_entries" DROP CONSTRAINT "FK_f5e6e5294e58a25e5c1225423a4"`);
        await queryRunner.query(`ALTER TABLE "items" DROP CONSTRAINT "FK_88f394967ca01158e3b2ef9a054"`);
        await queryRunner.query(`ALTER TABLE "items" DROP CONSTRAINT "FK_2896db8ca5f9fd7c5803c0532a6"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_42385e42f092f26bd38df549717"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_578080ec014d8d01c71b8581769"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_39a202af5d1dd1744458820ecb5"`);
        await queryRunner.query(`ALTER TABLE "account_balances" DROP CONSTRAINT "FK_0d2ca9b80d0de6fbbf33335ff5f"`);
        await queryRunner.query(`ALTER TABLE "account_balances" DROP CONSTRAINT "FK_8b991d69e7b47a9deb483b91dfa"`);
        await queryRunner.query(`ALTER TABLE "user_companies" DROP CONSTRAINT "FK_50c7d6aeb4ab214ad9fff29ab68"`);
        await queryRunner.query(`ALTER TABLE "user_companies" DROP CONSTRAINT "FK_9e735e90e4fd3bbb4268ed96d94"`);
        await queryRunner.query(`DROP INDEX "public"."idx_companies_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_email"`);
        await queryRunner.query(`DROP INDEX "public"."idx_fiscal_years_company"`);
        await queryRunner.query(`DROP INDEX "public"."idx_accounts_company"`);
        await queryRunner.query(`DROP INDEX "public"."idx_accounts_type"`);
        await queryRunner.query(`DROP INDEX "public"."idx_accounts_parent"`);
        await queryRunner.query(`DROP INDEX "public"."idx_accounts_posting"`);
        await queryRunner.query(`DROP INDEX "public"."idx_journal_lines_entry"`);
        await queryRunner.query(`DROP INDEX "public"."idx_journal_lines_account"`);
        await queryRunner.query(`DROP INDEX "public"."idx_journal_lines_cost_center"`);
        await queryRunner.query(`DROP INDEX "public"."idx_journal_company_date"`);
        await queryRunner.query(`DROP INDEX "public"."idx_journal_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_journal_voucher_type"`);
        await queryRunner.query(`DROP INDEX "public"."idx_journal_fiscal_year"`);
        await queryRunner.query(`DROP INDEX "public"."idx_invoice_lines_invoice"`);
        await queryRunner.query(`DROP INDEX "public"."idx_invoices_company"`);
        await queryRunner.query(`DROP INDEX "public"."idx_invoices_customer"`);
        await queryRunner.query(`DROP INDEX "public"."idx_invoices_supplier"`);
        await queryRunner.query(`DROP INDEX "public"."idx_invoices_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_balances_account"`);
        await queryRunner.query(`ALTER TABLE "companies" DROP CONSTRAINT "chk_fiscal_month"`);
        await queryRunner.query(`ALTER TABLE "fiscal_years" DROP CONSTRAINT "chk_date_range"`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP CONSTRAINT "chk_posting_level"`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP CONSTRAINT "chk_opening_balance_type"`);
        await queryRunner.query(`ALTER TABLE "journal_entry_lines" DROP CONSTRAINT "chk_debit_positive"`);
        await queryRunner.query(`ALTER TABLE "journal_entry_lines" DROP CONSTRAINT "chk_credit_positive"`);
        await queryRunner.query(`ALTER TABLE "journal_entry_lines" DROP CONSTRAINT "chk_debit_credit"`);
        await queryRunner.query(`ALTER TABLE "journal_entries" DROP CONSTRAINT "chk_posted"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "chk_customer_or_supplier"`);
        await queryRunner.query(`ALTER TABLE "voucher_types" DROP CONSTRAINT "uq_voucher_type"`);
        await queryRunner.query(`ALTER TABLE "fiscal_years" DROP CONSTRAINT "uq_fiscal_year"`);
        await queryRunner.query(`ALTER TABLE "tax_categories" DROP CONSTRAINT "uq_tax_code"`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP CONSTRAINT "uq_account_code"`);
        await queryRunner.query(`ALTER TABLE "cost_centers" DROP CONSTRAINT "uq_cost_center_code"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP CONSTRAINT "uq_customer_code"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "uq_project_code"`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP CONSTRAINT "uq_supplier_code"`);
        await queryRunner.query(`ALTER TABLE "journal_entry_lines" DROP CONSTRAINT "uq_line_no"`);
        await queryRunner.query(`ALTER TABLE "journal_entries" DROP CONSTRAINT "uq_voucher_no"`);
        await queryRunner.query(`ALTER TABLE "items" DROP CONSTRAINT "uq_item_code"`);
        await queryRunner.query(`ALTER TABLE "invoice_lines" DROP CONSTRAINT "uq_invoice_line"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "uq_invoice_no"`);
        await queryRunner.query(`CREATE TABLE "fixed_assets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "name" character varying NOT NULL, "description" character varying NOT NULL, "purchaseDate" date NOT NULL, "purchaseCost" numeric(18,2) NOT NULL, "salvageValue" numeric(18,2) NOT NULL, "usefulLifeYears" integer NOT NULL, "depreciationMethod" character varying NOT NULL DEFAULT 'STRAIGHT_LINE', "status" character varying NOT NULL DEFAULT 'ACTIVE', CONSTRAINT "PK_901984c25ddf1dcf11f1c7a70d8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "depreciation_schedules" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "fixed_asset_id" uuid NOT NULL, "scheduleDate" date NOT NULL, "amount" numeric(18,2) NOT NULL, "isPosted" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_f7d967d218b3fc888c6b55041be" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "currencies" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "code" character varying(3) NOT NULL, "name" character varying NOT NULL, "symbol" character varying(5) NOT NULL, "isBase" boolean NOT NULL DEFAULT false, "isActive" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_9f8d0972aeeb5a2277e40332d29" UNIQUE ("code"), CONSTRAINT "PK_d528c54860c4182db13548e08c4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "exchange_rates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "from_currency_id" uuid NOT NULL, "to_currency_id" uuid NOT NULL, "rate" numeric(18,6) NOT NULL, "validFrom" date NOT NULL, CONSTRAINT "PK_33a614bad9e61956079d817ebe2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "cost_centers_closure" ("id_ancestor" uuid NOT NULL, "id_descendant" uuid NOT NULL, CONSTRAINT "PK_c39ba099b665595c97a6482c634" PRIMARY KEY ("id_ancestor", "id_descendant"))`);
        await queryRunner.query(`CREATE INDEX "IDX_29a1506ee541e721db8b2a166b" ON "cost_centers_closure" ("id_ancestor") `);
        await queryRunner.query(`CREATE INDEX "IDX_1354572a43adca094948c11eae" ON "cost_centers_closure" ("id_descendant") `);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "account_id"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "code"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "tax_registration_no"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "code"`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP COLUMN "account_id"`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP COLUMN "code"`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP COLUMN "tax_registration_no"`);
        await queryRunner.query(`ALTER TABLE "journal_entry_lines" DROP COLUMN "line_no"`);
        await queryRunner.query(`ALTER TABLE "journal_entry_lines" DROP COLUMN "tax_amount"`);
        await queryRunner.query(`ALTER TABLE "journal_entry_lines" DROP COLUMN "tax_category_id"`);
        await queryRunner.query(`ALTER TABLE "items" DROP COLUMN "unit_price"`);
        await queryRunner.query(`ALTER TABLE "items" DROP COLUMN "tax_category_id"`);
        await queryRunner.query(`ALTER TABLE "items" DROP COLUMN "code"`);
        await queryRunner.query(`ALTER TABLE "items" DROP COLUMN "type"`);
        await queryRunner.query(`ALTER TABLE "invoice_lines" DROP COLUMN "line_no"`);
        await queryRunner.query(`ALTER TABLE "invoice_lines" DROP COLUMN "discount_percent"`);
        await queryRunner.query(`ALTER TABLE "invoice_lines" DROP COLUMN "tax_percent"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "exchange_rate"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "voucher_id"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "created_by"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "invoice_no"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "currency_code"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "payment_terms"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "terms_conditions"`);
        await queryRunner.query(`ALTER TABLE "account_balances" DROP CONSTRAINT "PK_f44ebca575a6732e6953110baaa"`);
        await queryRunner.query(`ALTER TABLE "account_balances" ADD CONSTRAINT "PK_bb9e21885908329ccbeefbea286" PRIMARY KEY ("company_id", "account_id")`);
        await queryRunner.query(`ALTER TABLE "account_balances" DROP COLUMN "period"`);
        await queryRunner.query(`ALTER TABLE "account_balances" DROP COLUMN "opening_debit"`);
        await queryRunner.query(`ALTER TABLE "account_balances" DROP COLUMN "opening_credit"`);
        await queryRunner.query(`ALTER TABLE "account_balances" DROP COLUMN "period_debit"`);
        await queryRunner.query(`ALTER TABLE "account_balances" DROP COLUMN "period_credit"`);
        await queryRunner.query(`ALTER TABLE "account_balances" DROP COLUMN "closing_debit"`);
        await queryRunner.query(`ALTER TABLE "account_balances" DROP COLUMN "closing_credit"`);
        await queryRunner.query(`ALTER TABLE "account_balances" DROP CONSTRAINT "PK_bb9e21885908329ccbeefbea286"`);
        await queryRunner.query(`ALTER TABLE "account_balances" ADD CONSTRAINT "PK_8b991d69e7b47a9deb483b91dfa" PRIMARY KEY ("account_id")`);
        await queryRunner.query(`ALTER TABLE "account_balances" DROP COLUMN "company_id"`);
        await queryRunner.query(`ALTER TABLE "user_companies" DROP COLUMN "is_default"`);
        await queryRunner.query(`ALTER TABLE "user_companies" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "voucher_types" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "voucher_types" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "fiscal_years" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "fiscal_years" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "tax_categories" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "tax_categories" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "tax_categories" ADD "description" text`);
        await queryRunner.query(`CREATE TYPE "public"."tax_categories_type_enum" AS ENUM('vat', 'sales_tax', 'withholding_tax', 'income_tax', 'excise_tax', 'custom_duty')`);
        await queryRunner.query(`ALTER TABLE "tax_categories" ADD "type" "public"."tax_categories_type_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tax_categories" ADD "is_compound" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "tax_categories" ADD "tax_number" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "cost_centers" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "cost_centers" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "cost_centers" ADD "description" text`);
        await queryRunner.query(`ALTER TABLE "cost_centers" ADD "budget_amount" numeric(18,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cost_centers" ADD "actual_amount" numeric(18,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cost_centers" ADD "parentId" uuid`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "customer_code" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "mobile" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "city" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "state" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "country" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "postal_code" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "tax_number" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "credit_days" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "current_balance" numeric(18,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "notes" text`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "contact_person" character varying(200)`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "project_code" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "description" text`);
        await queryRunner.query(`CREATE TYPE "public"."projects_status_enum" AS ENUM('planning', 'in_progress', 'on_hold', 'completed', 'cancelled')`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "status" "public"."projects_status_enum" NOT NULL DEFAULT 'planning'`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "actual_cost" numeric(18,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "estimated_revenue" numeric(18,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "actual_revenue" numeric(18,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "project_manager" character varying(200)`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "notes" text`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "customer_id" uuid`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD "supplier_code" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD "mobile" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD "city" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD "state" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD "country" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD "postal_code" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD "tax_number" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD "payment_terms_days" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD "current_balance" numeric(18,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD "notes" text`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD "contact_person" character varying(200)`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD "rating" integer`);
        await queryRunner.query(`ALTER TABLE "reconciliations" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "reconciliations" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "journal_entry_lines" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "journal_entry_lines" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "journal_entry_lines" ADD "company_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "journal_entries" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "items" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "items" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "items" ADD "item_code" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "items" ADD "unit_of_measure" character varying(20) NOT NULL DEFAULT 'pcs'`);
        await queryRunner.query(`ALTER TABLE "items" ADD "sales_price" numeric(18,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "items" ADD "purchase_price" numeric(18,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "items" ADD "is_inventory_item" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "items" ADD "current_stock" numeric(18,4) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "items" ADD "reorder_level" numeric(18,4) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "items" ADD "barcode" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "items" ADD "sku" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "items" ADD "category" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "items" ADD "brand" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "items" ADD "sales_tax_category_id" uuid`);
        await queryRunner.query(`ALTER TABLE "items" ADD "purchase_tax_category_id" uuid`);
        await queryRunner.query(`ALTER TABLE "items" ADD "inventory_account_id" uuid`);
        await queryRunner.query(`ALTER TABLE "invoice_lines" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "invoice_lines" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "invoice_lines" ADD "line_number" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoice_lines" ADD "discount_percentage" numeric(5,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "invoice_lines" ADD "tax_percentage" numeric(5,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "invoice_lines" ADD "net_amount" numeric(18,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoice_lines" ADD "tax_category_id" uuid`);
        await queryRunner.query(`ALTER TABLE "invoice_lines" ADD "unit_of_measure" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "invoice_number" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "reference_number" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "description" text`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "terms" text`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "discount_percentage" numeric(5,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "is_recurring" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "recurring_frequency" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "next_invoice_date" date`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "attachment_url" character varying(500)`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "posted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "posted_by" uuid`);
        await queryRunner.query(`ALTER TABLE "account_balances" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "account_balances" DROP CONSTRAINT "PK_8b991d69e7b47a9deb483b91dfa"`);
        await queryRunner.query(`ALTER TABLE "account_balances" ADD CONSTRAINT "PK_1d466537d625790627fc7566c17" PRIMARY KEY ("account_id", "id")`);
        await queryRunner.query(`ALTER TABLE "account_balances" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "account_balances" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "account_balances" ADD "openingBalance" numeric(18,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "account_balances" ADD "debitAmount" numeric(18,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "account_balances" ADD "creditAmount" numeric(18,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "account_balances" ADD "closingBalance" numeric(18,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "companies" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "companies" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "companies" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "companies" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "companies" DROP COLUMN "legal_name"`);
        await queryRunner.query(`ALTER TABLE "companies" ADD "legal_name" character varying`);
        await queryRunner.query(`ALTER TABLE "companies" DROP COLUMN "registration_no"`);
        await queryRunner.query(`ALTER TABLE "companies" ADD "registration_no" character varying`);
        await queryRunner.query(`ALTER TABLE "companies" DROP COLUMN "tax_registration_no"`);
        await queryRunner.query(`ALTER TABLE "companies" ADD "tax_registration_no" character varying`);
        await queryRunner.query(`ALTER TABLE "companies" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "companies" ADD "phone" character varying`);
        await queryRunner.query(`ALTER TABLE "companies" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "companies" ADD "email" character varying`);
        await queryRunner.query(`ALTER TABLE "voucher_types" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "voucher_types" DROP COLUMN "code"`);
        await queryRunner.query(`ALTER TABLE "voucher_types" ADD "code" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "voucher_types" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "voucher_types" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."voucher_nature" RENAME TO "voucher_nature_old"`);
        await queryRunner.query(`CREATE TYPE "public"."voucher_types_nature_enum" AS ENUM('payment', 'receipt', 'journal', 'contra', 'sales', 'purchase', 'credit_note', 'debit_note', 'opening')`);
        await queryRunner.query(`ALTER TABLE "voucher_types" ALTER COLUMN "nature" TYPE "public"."voucher_types_nature_enum" USING "nature"::"text"::"public"."voucher_types_nature_enum"`);
        await queryRunner.query(`DROP TYPE "public"."voucher_nature_old"`);
        await queryRunner.query(`ALTER TABLE "voucher_types" DROP COLUMN "prefix"`);
        await queryRunner.query(`ALTER TABLE "voucher_types" ADD "prefix" character varying`);
        await queryRunner.query(`ALTER TABLE "voucher_types" DROP COLUMN "reset_frequency"`);
        await queryRunner.query(`ALTER TABLE "voucher_types" ADD "reset_frequency" character varying NOT NULL DEFAULT 'yearly'`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "email" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "password"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "password" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "first_name"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "first_name" character varying`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "last_name"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "last_name" character varying`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "phone" character varying`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "role"`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('super_admin', 'admin', 'accountant', 'manager', 'user')`);
        await queryRunner.query(`ALTER TABLE "users" ADD "role" "public"."users_role_enum" NOT NULL DEFAULT 'user'`);
        await queryRunner.query(`ALTER TABLE "fiscal_years" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "fiscal_years" DROP COLUMN "year_name"`);
        await queryRunner.query(`ALTER TABLE "fiscal_years" ADD "year_name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tax_categories" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "tax_categories" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "tax_categories" ADD "name" character varying(200) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "accounts" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "accounts" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP COLUMN "code"`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD "code" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."account_type" RENAME TO "account_type_old"`);
        await queryRunner.query(`CREATE TYPE "public"."accounts_type_enum" AS ENUM('asset', 'liability', 'equity', 'income', 'expense')`);
        await queryRunner.query(`ALTER TABLE "accounts" ALTER COLUMN "type" TYPE "public"."accounts_type_enum" USING "type"::"text"::"public"."accounts_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."account_type_old"`);
        await queryRunner.query(`ALTER TYPE "public"."account_level" RENAME TO "account_level_old"`);
        await queryRunner.query(`CREATE TYPE "public"."accounts_level_enum" AS ENUM('1', '2', '3', '4')`);
        await queryRunner.query(`ALTER TABLE "accounts" ALTER COLUMN "level" TYPE "public"."accounts_level_enum" USING "level"::"text"::"public"."accounts_level_enum"`);
        await queryRunner.query(`DROP TYPE "public"."account_level_old"`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP COLUMN "opening_balance_type"`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD "opening_balance_type" character varying`);
        await queryRunner.query(`ALTER TABLE "cost_centers" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "cost_centers" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "cost_centers" ADD "name" character varying(200) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "customers" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "name" character varying(200) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "email" character varying(200)`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "payment_terms"`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "payment_terms" text`);
        await queryRunner.query(`ALTER TABLE "projects" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "name" character varying(200) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "projects" ALTER COLUMN "budget_amount" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "projects" ALTER COLUMN "budget_amount" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "suppliers" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD "name" character varying(200) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD "email" character varying(200)`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP COLUMN "payment_terms"`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD "payment_terms" text`);
        await queryRunner.query(`ALTER TABLE "reconciliations" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "journal_entry_lines" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "journal_entries" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "journal_entries" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "journal_entries" DROP COLUMN "voucher_no"`);
        await queryRunner.query(`ALTER TABLE "journal_entries" ADD "voucher_no" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "journal_entries" DROP COLUMN "reference"`);
        await queryRunner.query(`ALTER TABLE "journal_entries" ADD "reference" character varying`);
        await queryRunner.query(`ALTER TABLE "journal_entries" DROP COLUMN "source_module"`);
        await queryRunner.query(`ALTER TABLE "journal_entries" ADD "source_module" character varying`);
        await queryRunner.query(`ALTER TYPE "public"."entry_status" RENAME TO "entry_status_old"`);
        await queryRunner.query(`CREATE TYPE "public"."journal_entries_status_enum" AS ENUM('draft', 'pending_approval', 'approved', 'posted', 'cancelled', 'reversed')`);
        await queryRunner.query(`ALTER TABLE "journal_entries" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "journal_entries" ALTER COLUMN "status" TYPE "public"."journal_entries_status_enum" USING "status"::"text"::"public"."journal_entries_status_enum"`);
        await queryRunner.query(`ALTER TABLE "journal_entries" ALTER COLUMN "status" SET DEFAULT 'draft'`);
        await queryRunner.query(`DROP TYPE "public"."entry_status_old"`);
        await queryRunner.query(`ALTER TABLE "journal_entries" DROP COLUMN "reversed_by_id"`);
        await queryRunner.query(`ALTER TABLE "journal_entries" ADD "reversed_by_id" character varying`);
        await queryRunner.query(`ALTER TABLE "journal_entries" DROP COLUMN "reversal_of_id"`);
        await queryRunner.query(`ALTER TABLE "journal_entries" ADD "reversal_of_id" character varying`);
        await queryRunner.query(`ALTER TABLE "items" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "items" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "items" ADD "name" character varying(200) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoice_lines" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "invoice_lines" ALTER COLUMN "quantity" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TYPE "public"."invoice_type" RENAME TO "invoice_type_old"`);
        await queryRunner.query(`CREATE TYPE "public"."invoices_invoice_type_enum" AS ENUM('sales', 'purchase')`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "invoice_type" TYPE "public"."invoices_invoice_type_enum" USING "invoice_type"::"text"::"public"."invoices_invoice_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."invoice_type_old"`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "due_date" DROP NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."invoice_status" RENAME TO "invoice_status_old"`);
        await queryRunner.query(`CREATE TYPE "public"."invoices_status_enum" AS ENUM('draft', 'issued', 'partially_paid', 'paid', 'cancelled', 'overdue')`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "status" TYPE "public"."invoices_status_enum" USING "status"::"text"::"public"."invoices_status_enum"`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "status" SET DEFAULT 'draft'`);
        await queryRunner.query(`DROP TYPE "public"."invoice_status_old"`);
        await queryRunner.query(`ALTER TABLE "invoices" RENAME COLUMN "balance_amount" TO "TEMP_OLD_balance_amount"`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "balance_amount" numeric(18,2) NOT NULL`);
        await queryRunner.query(`UPDATE "invoices" SET "balance_amount" = "TEMP_OLD_balance_amount"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "TEMP_OLD_balance_amount"`);
        await queryRunner.query(`DELETE FROM "typeorm_metadata" WHERE "type" = $1 AND "name" = $2 AND "database" = $3 AND "schema" = $4 AND "table" = $5`, ["GENERATED_COLUMN","balance_amount","lab-accounts","public","invoices"]);
        await queryRunner.query(`ALTER TABLE "account_balances" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "account_balances" DROP CONSTRAINT "PK_1d466537d625790627fc7566c17"`);
        await queryRunner.query(`ALTER TABLE "account_balances" ADD CONSTRAINT "PK_919c1ceca951a4fd7b93532a3b1" PRIMARY KEY ("id")`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_acca5c144333c1c54bc947b3a1" ON "tax_categories" ("company_id", "code") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_306bfdf3933f89c53e5e26421c" ON "cost_centers" ("company_id", "code") `);
        await queryRunner.query(`CREATE INDEX "IDX_946a7a5519eab49537ba6be271" ON "customers" ("company_id", "email") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_3e47f55545cf7b43e6b920adcf" ON "customers" ("company_id", "customer_code") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_df49c1eebeba7d847aabf8a216" ON "projects" ("company_id", "project_code") `);
        await queryRunner.query(`CREATE INDEX "IDX_847616e0ec0a0296a7a6bce1a2" ON "suppliers" ("company_id", "email") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_28e22bb0f3f325d692f5745926" ON "suppliers" ("company_id", "supplier_code") `);
        await queryRunner.query(`CREATE INDEX "IDX_ae4efc73cd501302f030b2a51b" ON "items" ("company_id", "name") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_669b279373db7c59e0b0139b9b" ON "items" ("company_id", "item_code") `);
        await queryRunner.query(`CREATE INDEX "IDX_2da95dc86a54a00ff20ce46d0f" ON "invoice_lines" ("invoice_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_7e6bdc8f1b0f0208440b721bf3" ON "invoices" ("company_id", "supplier_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f243bae129d662d79b47ff4e67" ON "invoices" ("company_id", "customer_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_822d14bc3fd752a68418d755c9" ON "invoices" ("company_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_329ed73fcc667a3d370e9e8e06" ON "invoices" ("company_id", "invoice_date") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_c72926e1735b41a93b9c5f57c0" ON "invoices" ("company_id", "invoice_number") `);
        await queryRunner.query(`CREATE INDEX "IDX_50c7d6aeb4ab214ad9fff29ab6" ON "user_companies" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_9e735e90e4fd3bbb4268ed96d9" ON "user_companies" ("company_id") `);
        await queryRunner.query(`ALTER TABLE "voucher_types" ADD CONSTRAINT "FK_189fe983f7ad425d7b9399deb11" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fiscal_years" ADD CONSTRAINT "FK_12c06a42d8814383cfeca9abc83" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tax_categories" ADD CONSTRAINT "FK_3dc030fc235c86c139927bbfa55" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD CONSTRAINT "FK_b22c8136b3e83352b0013224801" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD CONSTRAINT "FK_f7ea327e4100ce4d6002ecdd12b" FOREIGN KEY ("parent_id") REFERENCES "accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cost_centers" ADD CONSTRAINT "FK_966404fc47b7566686a92802ef9" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cost_centers" ADD CONSTRAINT "FK_fdcf4a9d3d759f6b69c09c7b9e9" FOREIGN KEY ("parentId") REFERENCES "cost_centers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customers" ADD CONSTRAINT "FK_f0e29920aaf871f3eddbea69f0d" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_c8708288b8e6a060ed7b9e1a226" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_8ee9cae5efccf846467e1cb005c" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD CONSTRAINT "FK_6a9681499416e80c1ffac4fe86c" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reconciliations" ADD CONSTRAINT "FK_a895f63f3a83d3c7bbaf2f3d6e0" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "journal_entry_lines" ADD CONSTRAINT "FK_72c574f7b3968f2876604547f82" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "journal_entry_lines" ADD CONSTRAINT "FK_4a4fcd732e7b109880444ebc9c1" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "journal_entries" ADD CONSTRAINT "FK_435ac51210483ad504efff69a40" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "items" ADD CONSTRAINT "FK_88f394967ca01158e3b2ef9a054" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "items" ADD CONSTRAINT "FK_3ba4884b15d88d3d6095a3cd278" FOREIGN KEY ("sales_tax_category_id") REFERENCES "tax_categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "items" ADD CONSTRAINT "FK_4f68394bd47cf3d46563d4975f2" FOREIGN KEY ("purchase_tax_category_id") REFERENCES "tax_categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "items" ADD CONSTRAINT "FK_ff6462bc600b356cb9ed3814587" FOREIGN KEY ("inventory_account_id") REFERENCES "accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoice_lines" ADD CONSTRAINT "FK_addf5ed2cf0f6c366da28dd9d1b" FOREIGN KEY ("tax_category_id") REFERENCES "tax_categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_42385e42f092f26bd38df549717" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "depreciation_schedules" ADD CONSTRAINT "FK_e1b1d40dfb94d8a341eada2e7ae" FOREIGN KEY ("fixed_asset_id") REFERENCES "fixed_assets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "exchange_rates" ADD CONSTRAINT "FK_b2ef436f4da7ada3cf6b5c27f4c" FOREIGN KEY ("from_currency_id") REFERENCES "currencies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "exchange_rates" ADD CONSTRAINT "FK_437913540d381a4e268a682ee94" FOREIGN KEY ("to_currency_id") REFERENCES "currencies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "budgets" ADD CONSTRAINT "FK_08e12ed853dff5bbc38849cf7f4" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "budgets" ADD CONSTRAINT "FK_6c5af4f801dde8e6a73104c8b50" FOREIGN KEY ("fiscal_year_id") REFERENCES "fiscal_years"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "account_balances" ADD CONSTRAINT "FK_8b991d69e7b47a9deb483b91dfa" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_companies" ADD CONSTRAINT "FK_50c7d6aeb4ab214ad9fff29ab68" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_companies" ADD CONSTRAINT "FK_9e735e90e4fd3bbb4268ed96d94" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "cost_centers_closure" ADD CONSTRAINT "FK_29a1506ee541e721db8b2a166b9" FOREIGN KEY ("id_ancestor") REFERENCES "cost_centers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cost_centers_closure" ADD CONSTRAINT "FK_1354572a43adca094948c11eaea" FOREIGN KEY ("id_descendant") REFERENCES "cost_centers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "cost_centers_closure" DROP CONSTRAINT "FK_1354572a43adca094948c11eaea"`);
        await queryRunner.query(`ALTER TABLE "cost_centers_closure" DROP CONSTRAINT "FK_29a1506ee541e721db8b2a166b9"`);
        await queryRunner.query(`ALTER TABLE "user_companies" DROP CONSTRAINT "FK_9e735e90e4fd3bbb4268ed96d94"`);
        await queryRunner.query(`ALTER TABLE "user_companies" DROP CONSTRAINT "FK_50c7d6aeb4ab214ad9fff29ab68"`);
        await queryRunner.query(`ALTER TABLE "account_balances" DROP CONSTRAINT "FK_8b991d69e7b47a9deb483b91dfa"`);
        await queryRunner.query(`ALTER TABLE "budgets" DROP CONSTRAINT "FK_6c5af4f801dde8e6a73104c8b50"`);
        await queryRunner.query(`ALTER TABLE "budgets" DROP CONSTRAINT "FK_08e12ed853dff5bbc38849cf7f4"`);
        await queryRunner.query(`ALTER TABLE "exchange_rates" DROP CONSTRAINT "FK_437913540d381a4e268a682ee94"`);
        await queryRunner.query(`ALTER TABLE "exchange_rates" DROP CONSTRAINT "FK_b2ef436f4da7ada3cf6b5c27f4c"`);
        await queryRunner.query(`ALTER TABLE "depreciation_schedules" DROP CONSTRAINT "FK_e1b1d40dfb94d8a341eada2e7ae"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_42385e42f092f26bd38df549717"`);
        await queryRunner.query(`ALTER TABLE "invoice_lines" DROP CONSTRAINT "FK_addf5ed2cf0f6c366da28dd9d1b"`);
        await queryRunner.query(`ALTER TABLE "items" DROP CONSTRAINT "FK_ff6462bc600b356cb9ed3814587"`);
        await queryRunner.query(`ALTER TABLE "items" DROP CONSTRAINT "FK_4f68394bd47cf3d46563d4975f2"`);
        await queryRunner.query(`ALTER TABLE "items" DROP CONSTRAINT "FK_3ba4884b15d88d3d6095a3cd278"`);
        await queryRunner.query(`ALTER TABLE "items" DROP CONSTRAINT "FK_88f394967ca01158e3b2ef9a054"`);
        await queryRunner.query(`ALTER TABLE "journal_entries" DROP CONSTRAINT "FK_435ac51210483ad504efff69a40"`);
        await queryRunner.query(`ALTER TABLE "journal_entry_lines" DROP CONSTRAINT "FK_4a4fcd732e7b109880444ebc9c1"`);
        await queryRunner.query(`ALTER TABLE "journal_entry_lines" DROP CONSTRAINT "FK_72c574f7b3968f2876604547f82"`);
        await queryRunner.query(`ALTER TABLE "reconciliations" DROP CONSTRAINT "FK_a895f63f3a83d3c7bbaf2f3d6e0"`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP CONSTRAINT "FK_6a9681499416e80c1ffac4fe86c"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_8ee9cae5efccf846467e1cb005c"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_c8708288b8e6a060ed7b9e1a226"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP CONSTRAINT "FK_f0e29920aaf871f3eddbea69f0d"`);
        await queryRunner.query(`ALTER TABLE "cost_centers" DROP CONSTRAINT "FK_fdcf4a9d3d759f6b69c09c7b9e9"`);
        await queryRunner.query(`ALTER TABLE "cost_centers" DROP CONSTRAINT "FK_966404fc47b7566686a92802ef9"`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP CONSTRAINT "FK_f7ea327e4100ce4d6002ecdd12b"`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP CONSTRAINT "FK_b22c8136b3e83352b0013224801"`);
        await queryRunner.query(`ALTER TABLE "tax_categories" DROP CONSTRAINT "FK_3dc030fc235c86c139927bbfa55"`);
        await queryRunner.query(`ALTER TABLE "fiscal_years" DROP CONSTRAINT "FK_12c06a42d8814383cfeca9abc83"`);
        await queryRunner.query(`ALTER TABLE "voucher_types" DROP CONSTRAINT "FK_189fe983f7ad425d7b9399deb11"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9e735e90e4fd3bbb4268ed96d9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_50c7d6aeb4ab214ad9fff29ab6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c72926e1735b41a93b9c5f57c0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_329ed73fcc667a3d370e9e8e06"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_822d14bc3fd752a68418d755c9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f243bae129d662d79b47ff4e67"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7e6bdc8f1b0f0208440b721bf3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2da95dc86a54a00ff20ce46d0f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_669b279373db7c59e0b0139b9b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ae4efc73cd501302f030b2a51b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_28e22bb0f3f325d692f5745926"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_847616e0ec0a0296a7a6bce1a2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_df49c1eebeba7d847aabf8a216"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3e47f55545cf7b43e6b920adcf"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_946a7a5519eab49537ba6be271"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_306bfdf3933f89c53e5e26421c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_acca5c144333c1c54bc947b3a1"`);
        await queryRunner.query(`ALTER TABLE "account_balances" DROP CONSTRAINT "PK_919c1ceca951a4fd7b93532a3b1"`);
        await queryRunner.query(`ALTER TABLE "account_balances" ADD CONSTRAINT "PK_1d466537d625790627fc7566c17" PRIMARY KEY ("account_id", "id")`);
        await queryRunner.query(`ALTER TABLE "account_balances" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "balance_amount"`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "balance_amount" numeric(18,2) GENERATED ALWAYS AS (total_amount - paid_amount) STORED NOT NULL`);
        await queryRunner.query(`INSERT INTO "typeorm_metadata"("database", "schema", "table", "type", "name", "value") VALUES ($1, $2, $3, $4, $5, $6)`, ["lab-accounts","public","invoices","GENERATED_COLUMN","balance_amount","total_amount - paid_amount"]);
        await queryRunner.query(`CREATE TYPE "public"."invoice_status_old" AS ENUM('draft', 'issued', 'partially_paid', 'paid', 'overdue', 'cancelled')`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "status" TYPE "public"."invoice_status_old" USING "status"::"text"::"public"."invoice_status_old"`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "status" SET DEFAULT 'draft'`);
        await queryRunner.query(`DROP TYPE "public"."invoices_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."invoice_status_old" RENAME TO "invoice_status"`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "due_date" SET NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."invoice_type_old" AS ENUM('sales', 'purchase')`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "invoice_type" TYPE "public"."invoice_type_old" USING "invoice_type"::"text"::"public"."invoice_type_old"`);
        await queryRunner.query(`DROP TYPE "public"."invoices_invoice_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."invoice_type_old" RENAME TO "invoice_type"`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "invoice_lines" ALTER COLUMN "quantity" SET DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE "invoice_lines" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "items" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "items" ADD "name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "items" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "journal_entries" DROP COLUMN "reversal_of_id"`);
        await queryRunner.query(`ALTER TABLE "journal_entries" ADD "reversal_of_id" uuid`);
        await queryRunner.query(`ALTER TABLE "journal_entries" DROP COLUMN "reversed_by_id"`);
        await queryRunner.query(`ALTER TABLE "journal_entries" ADD "reversed_by_id" uuid`);
        await queryRunner.query(`CREATE TYPE "public"."entry_status_old" AS ENUM('draft', 'pending_approval', 'approved', 'posted', 'cancelled', 'reversed')`);
        await queryRunner.query(`ALTER TABLE "journal_entries" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "journal_entries" ALTER COLUMN "status" TYPE "public"."entry_status_old" USING "status"::"text"::"public"."entry_status_old"`);
        await queryRunner.query(`ALTER TABLE "journal_entries" ALTER COLUMN "status" SET DEFAULT 'draft'`);
        await queryRunner.query(`DROP TYPE "public"."journal_entries_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."entry_status_old" RENAME TO "entry_status"`);
        await queryRunner.query(`ALTER TABLE "journal_entries" DROP COLUMN "source_module"`);
        await queryRunner.query(`ALTER TABLE "journal_entries" ADD "source_module" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "journal_entries" DROP COLUMN "reference"`);
        await queryRunner.query(`ALTER TABLE "journal_entries" ADD "reference" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "journal_entries" DROP COLUMN "voucher_no"`);
        await queryRunner.query(`ALTER TABLE "journal_entries" ADD "voucher_no" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "journal_entries" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "journal_entries" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "journal_entry_lines" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "reconciliations" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP COLUMN "payment_terms"`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD "payment_terms" integer NOT NULL DEFAULT '30'`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD "email" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD "name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "suppliers" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "projects" ALTER COLUMN "budget_amount" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "projects" ALTER COLUMN "budget_amount" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "projects" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "payment_terms"`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "payment_terms" integer NOT NULL DEFAULT '30'`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "email" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "customers" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "cost_centers" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "cost_centers" ADD "name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "cost_centers" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP COLUMN "opening_balance_type"`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD "opening_balance_type" character varying(6)`);
        await queryRunner.query(`CREATE TYPE "public"."account_level_old" AS ENUM('1', '2', '3', '4')`);
        await queryRunner.query(`ALTER TABLE "accounts" ALTER COLUMN "level" TYPE "public"."account_level_old" USING "level"::"text"::"public"."account_level_old"`);
        await queryRunner.query(`DROP TYPE "public"."accounts_level_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."account_level_old" RENAME TO "account_level"`);
        await queryRunner.query(`CREATE TYPE "public"."account_type_old" AS ENUM('asset', 'liability', 'equity', 'income', 'expense')`);
        await queryRunner.query(`ALTER TABLE "accounts" ALTER COLUMN "type" TYPE "public"."account_type_old" USING "type"::"text"::"public"."account_type_old"`);
        await queryRunner.query(`DROP TYPE "public"."accounts_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."account_type_old" RENAME TO "account_type"`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD "name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP COLUMN "code"`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD "code" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "accounts" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "accounts" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "tax_categories" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "tax_categories" ADD "name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tax_categories" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "fiscal_years" DROP COLUMN "year_name"`);
        await queryRunner.query(`ALTER TABLE "fiscal_years" ADD "year_name" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "fiscal_years" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "role"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "role" character varying(50) NOT NULL DEFAULT 'user'`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "phone" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "last_name"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "last_name" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "first_name"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "first_name" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "password"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "password" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "email" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "voucher_types" DROP COLUMN "reset_frequency"`);
        await queryRunner.query(`ALTER TABLE "voucher_types" ADD "reset_frequency" character varying(20) NOT NULL DEFAULT 'yearly'`);
        await queryRunner.query(`ALTER TABLE "voucher_types" DROP COLUMN "prefix"`);
        await queryRunner.query(`ALTER TABLE "voucher_types" ADD "prefix" character varying(20)`);
        await queryRunner.query(`CREATE TYPE "public"."voucher_nature_old" AS ENUM('payment', 'receipt', 'journal', 'contra', 'sales', 'purchase', 'credit_note', 'debit_note', 'opening')`);
        await queryRunner.query(`ALTER TABLE "voucher_types" ALTER COLUMN "nature" TYPE "public"."voucher_nature_old" USING "nature"::"text"::"public"."voucher_nature_old"`);
        await queryRunner.query(`DROP TYPE "public"."voucher_types_nature_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."voucher_nature_old" RENAME TO "voucher_nature"`);
        await queryRunner.query(`ALTER TABLE "voucher_types" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "voucher_types" ADD "name" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "voucher_types" DROP COLUMN "code"`);
        await queryRunner.query(`ALTER TABLE "voucher_types" ADD "code" character varying(10) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "voucher_types" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "companies" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "companies" ADD "email" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "companies" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "companies" ADD "phone" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "companies" DROP COLUMN "tax_registration_no"`);
        await queryRunner.query(`ALTER TABLE "companies" ADD "tax_registration_no" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "companies" DROP COLUMN "registration_no"`);
        await queryRunner.query(`ALTER TABLE "companies" ADD "registration_no" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "companies" DROP COLUMN "legal_name"`);
        await queryRunner.query(`ALTER TABLE "companies" ADD "legal_name" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "companies" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "companies" ADD "name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "companies" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "companies" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "account_balances" DROP COLUMN "closingBalance"`);
        await queryRunner.query(`ALTER TABLE "account_balances" DROP COLUMN "creditAmount"`);
        await queryRunner.query(`ALTER TABLE "account_balances" DROP COLUMN "debitAmount"`);
        await queryRunner.query(`ALTER TABLE "account_balances" DROP COLUMN "openingBalance"`);
        await queryRunner.query(`ALTER TABLE "account_balances" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "account_balances" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "account_balances" DROP CONSTRAINT "PK_1d466537d625790627fc7566c17"`);
        await queryRunner.query(`ALTER TABLE "account_balances" ADD CONSTRAINT "PK_8b991d69e7b47a9deb483b91dfa" PRIMARY KEY ("account_id")`);
        await queryRunner.query(`ALTER TABLE "account_balances" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "posted_by"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "posted_at"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "attachment_url"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "next_invoice_date"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "recurring_frequency"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "is_recurring"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "discount_percentage"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "terms"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "reference_number"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "invoice_number"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "invoice_lines" DROP COLUMN "unit_of_measure"`);
        await queryRunner.query(`ALTER TABLE "invoice_lines" DROP COLUMN "tax_category_id"`);
        await queryRunner.query(`ALTER TABLE "invoice_lines" DROP COLUMN "net_amount"`);
        await queryRunner.query(`ALTER TABLE "invoice_lines" DROP COLUMN "tax_percentage"`);
        await queryRunner.query(`ALTER TABLE "invoice_lines" DROP COLUMN "discount_percentage"`);
        await queryRunner.query(`ALTER TABLE "invoice_lines" DROP COLUMN "line_number"`);
        await queryRunner.query(`ALTER TABLE "invoice_lines" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "invoice_lines" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "items" DROP COLUMN "inventory_account_id"`);
        await queryRunner.query(`ALTER TABLE "items" DROP COLUMN "purchase_tax_category_id"`);
        await queryRunner.query(`ALTER TABLE "items" DROP COLUMN "sales_tax_category_id"`);
        await queryRunner.query(`ALTER TABLE "items" DROP COLUMN "brand"`);
        await queryRunner.query(`ALTER TABLE "items" DROP COLUMN "category"`);
        await queryRunner.query(`ALTER TABLE "items" DROP COLUMN "sku"`);
        await queryRunner.query(`ALTER TABLE "items" DROP COLUMN "barcode"`);
        await queryRunner.query(`ALTER TABLE "items" DROP COLUMN "reorder_level"`);
        await queryRunner.query(`ALTER TABLE "items" DROP COLUMN "current_stock"`);
        await queryRunner.query(`ALTER TABLE "items" DROP COLUMN "is_inventory_item"`);
        await queryRunner.query(`ALTER TABLE "items" DROP COLUMN "purchase_price"`);
        await queryRunner.query(`ALTER TABLE "items" DROP COLUMN "sales_price"`);
        await queryRunner.query(`ALTER TABLE "items" DROP COLUMN "unit_of_measure"`);
        await queryRunner.query(`ALTER TABLE "items" DROP COLUMN "item_code"`);
        await queryRunner.query(`ALTER TABLE "items" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "items" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "journal_entries" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "journal_entry_lines" DROP COLUMN "company_id"`);
        await queryRunner.query(`ALTER TABLE "journal_entry_lines" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "journal_entry_lines" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "reconciliations" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "reconciliations" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP COLUMN "rating"`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP COLUMN "contact_person"`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP COLUMN "current_balance"`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP COLUMN "payment_terms_days"`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP COLUMN "tax_number"`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP COLUMN "postal_code"`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP COLUMN "country"`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP COLUMN "state"`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP COLUMN "city"`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP COLUMN "mobile"`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP COLUMN "supplier_code"`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "customer_id"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "project_manager"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "actual_revenue"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "estimated_revenue"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "actual_cost"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."projects_status_enum"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "project_code"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "contact_person"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "current_balance"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "credit_days"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "tax_number"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "postal_code"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "country"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "state"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "city"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "mobile"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "customer_code"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "cost_centers" DROP COLUMN "parentId"`);
        await queryRunner.query(`ALTER TABLE "cost_centers" DROP COLUMN "actual_amount"`);
        await queryRunner.query(`ALTER TABLE "cost_centers" DROP COLUMN "budget_amount"`);
        await queryRunner.query(`ALTER TABLE "cost_centers" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "cost_centers" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "cost_centers" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "tax_categories" DROP COLUMN "tax_number"`);
        await queryRunner.query(`ALTER TABLE "tax_categories" DROP COLUMN "is_compound"`);
        await queryRunner.query(`ALTER TABLE "tax_categories" DROP COLUMN "type"`);
        await queryRunner.query(`DROP TYPE "public"."tax_categories_type_enum"`);
        await queryRunner.query(`ALTER TABLE "tax_categories" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "tax_categories" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "tax_categories" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "fiscal_years" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "fiscal_years" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "voucher_types" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "voucher_types" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "user_companies" ADD "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "user_companies" ADD "is_default" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "account_balances" ADD "company_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "account_balances" DROP CONSTRAINT "PK_8b991d69e7b47a9deb483b91dfa"`);
        await queryRunner.query(`ALTER TABLE "account_balances" ADD CONSTRAINT "PK_bb9e21885908329ccbeefbea286" PRIMARY KEY ("company_id", "account_id")`);
        await queryRunner.query(`ALTER TABLE "account_balances" ADD "closing_credit" numeric(18,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "account_balances" ADD "closing_debit" numeric(18,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "account_balances" ADD "period_credit" numeric(18,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "account_balances" ADD "period_debit" numeric(18,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "account_balances" ADD "opening_credit" numeric(18,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "account_balances" ADD "opening_debit" numeric(18,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "account_balances" ADD "period" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "account_balances" DROP CONSTRAINT "PK_bb9e21885908329ccbeefbea286"`);
        await queryRunner.query(`ALTER TABLE "account_balances" ADD CONSTRAINT "PK_f44ebca575a6732e6953110baaa" PRIMARY KEY ("period", "company_id", "account_id")`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "terms_conditions" text`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "payment_terms" text`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "currency_code" character varying(3) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "invoice_no" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "created_by" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "voucher_id" uuid`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "exchange_rate" numeric(18,6) NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE "invoice_lines" ADD "tax_percent" numeric(5,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "invoice_lines" ADD "discount_percent" numeric(5,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "invoice_lines" ADD "line_no" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "items" ADD "type" character varying(20) NOT NULL DEFAULT 'service'`);
        await queryRunner.query(`ALTER TABLE "items" ADD "code" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "items" ADD "tax_category_id" uuid`);
        await queryRunner.query(`ALTER TABLE "items" ADD "unit_price" numeric(18,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "journal_entry_lines" ADD "tax_category_id" uuid`);
        await queryRunner.query(`ALTER TABLE "journal_entry_lines" ADD "tax_amount" numeric(18,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "journal_entry_lines" ADD "line_no" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD "tax_registration_no" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD "code" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD "account_id" uuid`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "code" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "tax_registration_no" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "code" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "account_id" uuid`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1354572a43adca094948c11eae"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_29a1506ee541e721db8b2a166b"`);
        await queryRunner.query(`DROP TABLE "cost_centers_closure"`);
        await queryRunner.query(`DROP TABLE "budgets"`);
        await queryRunner.query(`DROP TABLE "exchange_rates"`);
        await queryRunner.query(`DROP TABLE "currencies"`);
        await queryRunner.query(`DROP TABLE "depreciation_schedules"`);
        await queryRunner.query(`DROP TABLE "fixed_assets"`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "uq_invoice_no" UNIQUE ("company_id", "invoice_no")`);
        await queryRunner.query(`ALTER TABLE "invoice_lines" ADD CONSTRAINT "uq_invoice_line" UNIQUE ("invoice_id", "line_no")`);
        await queryRunner.query(`ALTER TABLE "items" ADD CONSTRAINT "uq_item_code" UNIQUE ("company_id", "code")`);
        await queryRunner.query(`ALTER TABLE "journal_entries" ADD CONSTRAINT "uq_voucher_no" UNIQUE ("company_id", "voucher_no")`);
        await queryRunner.query(`ALTER TABLE "journal_entry_lines" ADD CONSTRAINT "uq_line_no" UNIQUE ("journal_entry_id", "line_no")`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD CONSTRAINT "uq_supplier_code" UNIQUE ("company_id", "code")`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "uq_project_code" UNIQUE ("company_id", "code")`);
        await queryRunner.query(`ALTER TABLE "customers" ADD CONSTRAINT "uq_customer_code" UNIQUE ("company_id", "code")`);
        await queryRunner.query(`ALTER TABLE "cost_centers" ADD CONSTRAINT "uq_cost_center_code" UNIQUE ("company_id", "code")`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD CONSTRAINT "uq_account_code" UNIQUE ("company_id", "code")`);
        await queryRunner.query(`ALTER TABLE "tax_categories" ADD CONSTRAINT "uq_tax_code" UNIQUE ("company_id", "code")`);
        await queryRunner.query(`ALTER TABLE "fiscal_years" ADD CONSTRAINT "uq_fiscal_year" UNIQUE ("company_id", "year_name")`);
        await queryRunner.query(`ALTER TABLE "voucher_types" ADD CONSTRAINT "uq_voucher_type" UNIQUE ("company_id", "code")`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "chk_customer_or_supplier" CHECK ((((invoice_type = 'sales'::invoice_type) AND (customer_id IS NOT NULL)) OR ((invoice_type = 'purchase'::invoice_type) AND (supplier_id IS NOT NULL))))`);
        await queryRunner.query(`ALTER TABLE "journal_entries" ADD CONSTRAINT "chk_posted" CHECK ((((posted = true) AND (posted_at IS NOT NULL)) OR (posted = false)))`);
        await queryRunner.query(`ALTER TABLE "journal_entry_lines" ADD CONSTRAINT "chk_debit_credit" CHECK ((((debit > (0)::numeric) AND (credit = (0)::numeric)) OR ((credit > (0)::numeric) AND (debit = (0)::numeric)) OR ((debit = (0)::numeric) AND (credit = (0)::numeric))))`);
        await queryRunner.query(`ALTER TABLE "journal_entry_lines" ADD CONSTRAINT "chk_credit_positive" CHECK ((credit >= (0)::numeric))`);
        await queryRunner.query(`ALTER TABLE "journal_entry_lines" ADD CONSTRAINT "chk_debit_positive" CHECK ((debit >= (0)::numeric))`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD CONSTRAINT "chk_opening_balance_type" CHECK (((opening_balance_type)::text = ANY ((ARRAY['debit'::character varying, 'credit'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD CONSTRAINT "chk_posting_level" CHECK ((((level = '4'::account_level) AND (is_posting = true)) OR ((level = ANY (ARRAY['1'::account_level, '2'::account_level, '3'::account_level])) AND (is_posting = false))))`);
        await queryRunner.query(`ALTER TABLE "fiscal_years" ADD CONSTRAINT "chk_date_range" CHECK ((end_date > start_date))`);
        await queryRunner.query(`ALTER TABLE "companies" ADD CONSTRAINT "chk_fiscal_month" CHECK (((fiscal_year_start_month >= 1) AND (fiscal_year_start_month <= 12)))`);
        await queryRunner.query(`CREATE INDEX "idx_balances_account" ON "account_balances" ("account_id", "period") `);
        await queryRunner.query(`CREATE INDEX "idx_invoices_status" ON "invoices" ("company_id", "status") `);
        await queryRunner.query(`CREATE INDEX "idx_invoices_supplier" ON "invoices" ("supplier_id") `);
        await queryRunner.query(`CREATE INDEX "idx_invoices_customer" ON "invoices" ("customer_id") `);
        await queryRunner.query(`CREATE INDEX "idx_invoices_company" ON "invoices" ("company_id", "invoice_date") `);
        await queryRunner.query(`CREATE INDEX "idx_invoice_lines_invoice" ON "invoice_lines" ("invoice_id") `);
        await queryRunner.query(`CREATE INDEX "idx_journal_fiscal_year" ON "journal_entries" ("fiscal_year_id") `);
        await queryRunner.query(`CREATE INDEX "idx_journal_voucher_type" ON "journal_entries" ("voucher_type_id") `);
        await queryRunner.query(`CREATE INDEX "idx_journal_status" ON "journal_entries" ("company_id", "status") `);
        await queryRunner.query(`CREATE INDEX "idx_journal_company_date" ON "journal_entries" ("company_id", "entry_date") `);
        await queryRunner.query(`CREATE INDEX "idx_journal_lines_cost_center" ON "journal_entry_lines" ("cost_center_id") `);
        await queryRunner.query(`CREATE INDEX "idx_journal_lines_account" ON "journal_entry_lines" ("account_id") `);
        await queryRunner.query(`CREATE INDEX "idx_journal_lines_entry" ON "journal_entry_lines" ("journal_entry_id") `);
        await queryRunner.query(`CREATE INDEX "idx_accounts_posting" ON "accounts" ("company_id", "is_posting") WHERE (is_posting = true)`);
        await queryRunner.query(`CREATE INDEX "idx_accounts_parent" ON "accounts" ("parent_id") `);
        await queryRunner.query(`CREATE INDEX "idx_accounts_type" ON "accounts" ("company_id", "type") `);
        await queryRunner.query(`CREATE INDEX "idx_accounts_company" ON "accounts" ("company_id") `);
        await queryRunner.query(`CREATE INDEX "idx_fiscal_years_company" ON "fiscal_years" ("company_id", "start_date") `);
        await queryRunner.query(`CREATE INDEX "idx_users_email" ON "users" ("email") `);
        await queryRunner.query(`CREATE INDEX "idx_companies_active" ON "companies" ("is_active") WHERE (deleted_at IS NULL)`);
        await queryRunner.query(`ALTER TABLE "user_companies" ADD CONSTRAINT "FK_9e735e90e4fd3bbb4268ed96d94" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_companies" ADD CONSTRAINT "FK_50c7d6aeb4ab214ad9fff29ab68" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "account_balances" ADD CONSTRAINT "FK_8b991d69e7b47a9deb483b91dfa" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "account_balances" ADD CONSTRAINT "FK_0d2ca9b80d0de6fbbf33335ff5f" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_39a202af5d1dd1744458820ecb5" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_578080ec014d8d01c71b8581769" FOREIGN KEY ("voucher_id") REFERENCES "journal_entries"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_42385e42f092f26bd38df549717" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "items" ADD CONSTRAINT "FK_2896db8ca5f9fd7c5803c0532a6" FOREIGN KEY ("tax_category_id") REFERENCES "tax_categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "items" ADD CONSTRAINT "FK_88f394967ca01158e3b2ef9a054" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "journal_entries" ADD CONSTRAINT "FK_f5e6e5294e58a25e5c1225423a4" FOREIGN KEY ("reversal_of_id") REFERENCES "journal_entries"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "journal_entries" ADD CONSTRAINT "FK_e077d1bd97565c550c745399139" FOREIGN KEY ("reversed_by_id") REFERENCES "journal_entries"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "journal_entries" ADD CONSTRAINT "FK_435ac51210483ad504efff69a40" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "journal_entry_lines" ADD CONSTRAINT "FK_b40d116356fb32866615bfa10d6" FOREIGN KEY ("tax_category_id") REFERENCES "tax_categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "journal_entry_lines" ADD CONSTRAINT "FK_4a4fcd732e7b109880444ebc9c1" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reconciliations" ADD CONSTRAINT "FK_a895f63f3a83d3c7bbaf2f3d6e0" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD CONSTRAINT "FK_62193e7cad0c29598758ad187d0" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD CONSTRAINT "FK_6a9681499416e80c1ffac4fe86c" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_c8708288b8e6a060ed7b9e1a226" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customers" ADD CONSTRAINT "FK_ebcc29963874e55053e8ee80be5" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customers" ADD CONSTRAINT "FK_f0e29920aaf871f3eddbea69f0d" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cost_centers" ADD CONSTRAINT "FK_966404fc47b7566686a92802ef9" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD CONSTRAINT "FK_f7ea327e4100ce4d6002ecdd12b" FOREIGN KEY ("parent_id") REFERENCES "accounts"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD CONSTRAINT "FK_b22c8136b3e83352b0013224801" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tax_categories" ADD CONSTRAINT "FK_3dc030fc235c86c139927bbfa55" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fiscal_years" ADD CONSTRAINT "FK_12c06a42d8814383cfeca9abc83" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "voucher_types" ADD CONSTRAINT "FK_189fe983f7ad425d7b9399deb11" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
